# Generated by Django 6.0.5 on 2026-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Interest rate for installments (0% = no interest)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='installment_months',
            field=models.JSONField(blank=True, default=list, help_text='Available installment months (e.g., [3, 6, 12]). Leave empty for default [3, 6, 12]'),
        ),
        migrations.AddField(
            model_name='product',
            name='lipa_pole_pole_eligible',
            field=models.BooleanField(default=False, help_text='Enable this product for Lipa Pole Pole installment payments'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['lipa_pole_pole_eligible', 'is_active'], name='products_pr_lipa_po_0c0200_idx'),
        ),
    ]
