# Generated by Django 6.0.5 on 2026-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_installment_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_lipa_po_0c0200_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='is_lipa_pole_pole',
            field=models.BooleanField(default=False, help_text='Check this box to show product in Lipa Mdogo Mdogo section.', verbose_name='Lipa Pole Pole Eligible'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_lipa_pole_pole', 'is_active'], name='products_pr_is_lipa_071e7a_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='lipa_pole_pole_eligible',
        ),
    ]
