# Generated by Django 6.0.5 on 2026-06-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_pr_lipa_po_0c0200_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('image', models.ImageField(help_text='Upload carousel slide image (recommended size: 1920x1080)', upload_to='carousel/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in carousel')),
                ('link_url', models.URLField(blank=True, help_text='Optional link when clicking the slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
