# Generated by Django 6.0.5 on 2026-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_carouselimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Carousel Image', 'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title (not displayed in current design)', max_length=200),
        ),
    ]
